/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iandroid_allclass_ccgame_room_CCGameRoomJNI */

#ifndef _Included_com_iandroid_allclass_ccgame_room_CCGameRoomJNI
#define _Included_com_iandroid_allclass_ccgame_room_CCGameRoomJNI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
