//
// Created by David on 2020/10/14.
//

#ifndef PROJ_ANDROID_COM_IANDROID_ALLCLASS_CCGAME_ROOM_CCGAMEROOMJNI_H
#define PROJ_ANDROID_COM_IANDROID_ALLCLASS_CCGAME_ROOM_CCGAMEROOMJNI_H

extern void onTouchedAvatar(int id);

extern void onTouchDown();

extern void onTouchUp();

#endif //PROJ_ANDROID_COM_IANDROID_ALLCLASS_CCGAME_ROOM_CCGAMEROOMJNI_H
